import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { getIndexableUrlsForPath, isAlwaysNoindexPath, normalizePublicPath } from "../src/lib/seo";
import { solutions } from "../src/data/solutionData";
import { industries } from "../src/data/industryData";
import { getAllTopicClusterPaths } from "../src/data/topicClusters";

const APP_FILE_PATH = path.resolve("src/App.tsx");
const OUTPUT_FILE_PATH = path.resolve("public/sitemap.xml");

function extractStaticPublicPaths(appSource: string): string[] {
  const paths = new Set<string>(["/"]);
  const routeMatches = appSource.matchAll(/path="([^"]+)"/g);

  for (const [, routePath] of routeMatches) {
    if (!routePath || routePath.startsWith("/")) {
      continue;
    }

    if (routePath === "*" || routePath.includes(":")) {
      continue;
    }

    const normalizedPath = normalizePublicPath(routePath);

    if (isAlwaysNoindexPath(normalizedPath)) {
      continue;
    }

    paths.add(normalizedPath);
  }

  return Array.from(paths);
}

function extractKnownDynamicPaths(): string[] {
  const paths = new Set<string>();

  Object.keys(solutions).forEach((slug) => {
    paths.add(normalizePublicPath(`/solutions/${slug}`));
  });

  Object.entries(industries).forEach(([slug, data]) => {
    if (!data.comingSoon) {
      paths.add(normalizePublicPath(`/industries/${slug}`));
    }
  });

  getAllTopicClusterPaths().forEach((pathname) => {
    paths.add(normalizePublicPath(pathname));
  });

  return Array.from(paths);
}

function buildSitemapXml(urlEntries: string[], lastModified: string): string {
  const urlNodes = urlEntries
    .map((url) =>
      [
        "  <url>",
        `    <loc>${url}</loc>`,
        `    <lastmod>${lastModified}</lastmod>`,
        "  </url>",
      ].join("\n"),
    )
    .join("\n");

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!-- Generated by scripts/generate-sitemap.ts. Do not edit manually. -->",
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    urlNodes,
    "</urlset>",
    "",
  ].join("\n");
}

async function main() {
  const appSource = await readFile(APP_FILE_PATH, "utf8");
  const staticPaths = extractStaticPublicPaths(appSource);
  const dynamicPaths = extractKnownDynamicPaths();
  const publicPaths = Array.from(new Set([...staticPaths, ...dynamicPaths]));
  const lastModified = new Date().toISOString().slice(0, 10);

  const urlEntries = publicPaths.flatMap((pathname) => getIndexableUrlsForPath(pathname));

  const uniqueSortedUrls = Array.from(new Set(urlEntries)).sort();
  const xml = buildSitemapXml(uniqueSortedUrls, lastModified);

  await mkdir(path.dirname(OUTPUT_FILE_PATH), { recursive: true });
  await writeFile(OUTPUT_FILE_PATH, xml, "utf8");

  console.log(`Generated sitemap with ${uniqueSortedUrls.length} URLs at ${OUTPUT_FILE_PATH}`);
}

main().catch((error) => {
  console.error("Failed to generate sitemap.");
  console.error(error);
  process.exitCode = 1;
});
